# config/redis.yml
default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  timeout: 1
  reconnect_attempts: 3

development:
  <<: *default
  db: 0

test:
  <<: *default
  db: 1

production:
  <<: *default
  db: 0